### ISSUE TITLE
Instructions in the README are accurate?

### ISSUE THREAD

**Issue by ofrobots** [filipesilva/angular-cli-perf-benchmark#6]
The README suggests cloning and then running `yarn`. There is no `package.json` in the repo, so this doesn't actually work.

Let me know if either the README or I am missing a step. Thanks!

**Comment by filipesilva** [comment]
Oh gosh, I'm so sorry, I didn't see this issue until now!

That part of the instructions is related to creating a new version of the benchmark package that is hosted on https://github.com/angular/angular-cli/tree/master/packages/angular_devkit/benchmark. 

But it's not really necessary because there's a local version here too. The instructions aren't very clear on how to install the local one. I'll reword them.
